[2024-05-22 10:17:36] INFO: Servidor iniciando.
[2024-05-22 10:17:38] INFO: Servidor iniciado com sucesso.
[2024-05-22 10:17:43] INFO: Verificando informações de login do usuário.
[2024-05-22 10:17:43] INFO: Usuário foi encontrado com sucesso.
[2024-05-22 10:17:44] ERROR: Não foi possível abrir a conexão com o banco!:
java.sql.SQLException: Erro ao executar a consulta da maquina no banco!
	at dao.MaquinaDAO.verifyMaquina(MaquinaDAO.java:102)
	at dao.MaquinaDAO.especificarMaquina(MaquinaDAO.java:53)
	at dao.MaquinaDAO.monitorarMaquina(MaquinaDAO.java:35)
	at service.ServicePC.verificarMaquina(ServicePC.java:18)
	at Main.main(Main.java:112)
Caused by: java.sql.SQLSyntaxErrorException: Table 'der_grupo_5.Maquina' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
	at dao.MaquinaDAO.verifyMaquina(MaquinaDAO.java:93)
	... 4 more

[2024-05-22 10:17:44] ERROR: Erro ao acessar máquina:
java.lang.RuntimeException: Erro ao abrir conexão com o banco!!
	at dao.MaquinaDAO.verifyMaquina(MaquinaDAO.java:106)
	at dao.MaquinaDAO.especificarMaquina(MaquinaDAO.java:53)
	at dao.MaquinaDAO.monitorarMaquina(MaquinaDAO.java:35)
	at service.ServicePC.verificarMaquina(ServicePC.java:18)
	at Main.main(Main.java:112)
Caused by: java.sql.SQLException: Erro ao executar a consulta da maquina no banco!
	at dao.MaquinaDAO.verifyMaquina(MaquinaDAO.java:102)
	... 4 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'der_grupo_5.Maquina' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
	at dao.MaquinaDAO.verifyMaquina(MaquinaDAO.java:93)
	... 4 more

[2024-05-22 10:17:44] WARNING: Não foi possível acessar a máquina do usuário
[2024-05-22 10:17:44] INFO: Usuário logado com sucesso: diego.santos@sptech.school
[2024-05-22 10:17:45] INFO: Buscando componentes...
[2024-05-22 10:17:45] ERROR: Ocorreu um erro ao obter seus componentes:
java.lang.NullPointerException: Cannot invoke "model.Maquina.getIdMaquina()" because "maquina" is null
	at dao.componente.ComponenteDAO.getComponentes(ComponenteDAO.java:20)
	at service.componente.ServiceComponente.obterComponentes(ServiceComponente.java:21)
	at Main.iniciarMonitoramento(Main.java:159)
	at Main.main(Main.java:133)

[2024-05-22 10:17:45] INFO: Capturando os componentes:

[2024-05-22 10:17:45] ERROR: Ocorreu um erro durante a captura:
java.lang.NullPointerException: Cannot invoke "model.Maquina.getComponentes()" because "maquina" is null
	at service.componente.ServiceComponente.iniciarCapturas(ServiceComponente.java:71)
	at Main.lambda$iniciarMonitoramento$0(Main.java:166)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[2024-05-22 10:17:48] ERROR: Ocorreu um erro durante a captura:
java.lang.NullPointerException: Cannot invoke "model.Maquina.getComponentes()" because "maquina" is null
	at service.componente.ServiceComponente.iniciarCapturas(ServiceComponente.java:71)
	at Main.lambda$iniciarMonitoramento$0(Main.java:166)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

